version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: playwright-test
    versions:
    - 3.0.1
    - 3.0.4
    - 3.0.5
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: airtap
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
  - dependency-name: buffer
    versions:
    - 6.0.3
